import type { Txn, FlaggedTxn, VerifAV, VerifKYB, SummaryRow } from "./types";
import {
  Clock, ShieldAlert, ArrowUpRight, CheckCircle2, X, Ban,
} from "lucide-react";

export const mockTxns: Txn[] = [
  { id:"2334519",    payee:"Vandelay Industries",  type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_APPROVE", amount:     99.99, cur:"GBP", trnDate:"25/03/2025", valDate:"25/03/2025", status:"Needs Approval", nextStatus:"Ready to Approve", processStage:"Approvals", risk:45, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Chase Bank",            legalEntity:"Ripple Treasury LLC",    approver:"A. Pacheco", approvalLevel:1, operativeAcct:"0A_CHASE_USD1",     offsetNumber:"2910784214", attachment:{ name:"Invoice-March2025.pdf", type:"pdf", url:"https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" } },
  { id:"2334520",    payee:"Vandelay Industries",  type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_APPROVE", amount:   4000.01, cur:"USD", trnDate:"25/03/2025", valDate:"25/03/2025", status:"Needs Approval", nextStatus:"Ready to Approve", processStage:"Approvals", risk:52, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Chase Bank",            legalEntity:"Ripple Treasury LLC",    approver:"A. Pacheco", approvalLevel:2, operativeAcct:"0A_CHASE_USD1",     offsetNumber:"2910784214" },
  { id:"2334720",    payee:"Tech Corp",            type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_APPROVE", amount:   4000.01, cur:"USD", trnDate:"25/03/2025", valDate:"25/03/2025", status:"Needs Approval", nextStatus:"Ready to Approve", processStage:"Approvals", risk:38, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Chase Bank",            legalEntity:"Ripple Treasury LLC",    approver:"A. Pacheco", approvalLevel:1, operativeAcct:"0A_CHASE_USD1",     offsetNumber:"2910784215", attachment:{ name:"Payment-Proof.pdf",    type:"pdf", url:"https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" } },
  { id:"FTR-100234", payee:"Fund A Account",       type:"Wire", instType:"WIRE",    modelId:"WIRE_APPROVE",     amount:1000000,    cur:"USD", trnDate:"13/02/2026", valDate:"13/02/2026", status:"Needs Approval", nextStatus:"Ready to Approve", processStage:"Approvals", risk:55, riskReason:"Large waterfall transfer · L1",riskFlag:null,       verified:true,  overdue:false, bank:"JPMorgan Chase",        legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:1, operativeAcct:"Master (****1234)",  offsetNumber:"****5678", rlusdEligible:true, waterfallChain:"WF-00042", waterfallPosition:1, waterfallTotal:4 },
  { id:"FTR-100235", payee:"Investment Account",   type:"Wire", instType:"WIRE",    modelId:"WIRE_APPROVE",     amount: 800000,    cur:"USD", trnDate:"13/02/2026", valDate:"13/02/2026", status:"Needs Approval", nextStatus:"Ready to Approve", processStage:"Approvals", risk:48, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"JPMorgan Chase",        legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:0, operativeAcct:"Fund A (****5678)",  offsetNumber:"****9012", rlusdEligible:true, waterfallChain:"WF-00042", waterfallPosition:2, waterfallTotal:4 },
  { id:"FTR-100236", payee:"Portfolio Company",    type:"Wire", instType:"WIRE",    modelId:"WIRE_APPROVE",     amount: 600000,    cur:"USD", trnDate:"13/02/2026", valDate:"13/02/2026", status:"Needs Approval", nextStatus:"Ready to Approve", processStage:"Approvals", risk:42, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"JPMorgan Chase",        legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:0, operativeAcct:"Invest (****9012)",  offsetNumber:"****3456", rlusdEligible:true, waterfallChain:"WF-00042", waterfallPosition:3, waterfallTotal:4 },
  { id:"FTR-100237", payee:"Operating Account",    type:"Wire", instType:"WIRE",    modelId:"WIRE_APPROVE",     amount: 400000,    cur:"USD", trnDate:"13/02/2026", valDate:"13/02/2026", status:"Needs Approval", nextStatus:"Ready to Approve", processStage:"Approvals", risk:38, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"JPMorgan Chase",        legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:0, operativeAcct:"Port Co (****3456)", offsetNumber:"****7890", rlusdEligible:true, waterfallChain:"WF-00042", waterfallPosition:4, waterfallTotal:4 },
  { id:"2334821",    payee:"Global Supplies",       type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_EXTRACT", amount:  15234.50, cur:"USD", trnDate:"24/03/2025", valDate:"24/03/2025", status:"Ready to Extract", nextStatus:"Processing",       processStage:"Status",    risk: 8, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Wells Fargo",           legalEntity:"Ripple Treasury US LLC", approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_WELLS_USD",       offsetNumber:"4512789632", attachment:{ name:"Remittance-Receipt.pdf",    type:"pdf", url:"https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" } },
  { id:"2334822",    payee:"European Partners",     type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_EXTRACT", amount:   8900.00, cur:"EUR", trnDate:"24/03/2025", valDate:"24/03/2025", status:"Ready to Extract", nextStatus:"Processing",       processStage:"Status",    risk:12, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"HSBC Europe",           legalEntity:"Ripple Treasury EU GmbH",approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_HSBC_EUR",        offsetNumber:"7823456789" },
  { id:"2334823",    payee:"UK Services Ltd",       type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_EXTRACT", amount:  52000.00, cur:"GBP", trnDate:"23/03/2025", valDate:"23/03/2025", status:"Ready to Extract", nextStatus:"Processing",       processStage:"Status",    risk:15, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Barclays",              legalEntity:"Ripple Treasury UK Ltd", approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_BARCLAYS_GBP",    offsetNumber:"9876543210", attachment:{ name:"Supporting-Documents.pdf", type:"pdf", url:"https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" } },
  { id:"2334724",    payee:"Manufacturing Inc",     type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_PROCESS",  amount:  32100.75, cur:"USD", trnDate:"22/03/2025", valDate:"22/03/2025", status:"Extracted",        nextStatus:"Confirmed",        processStage:"Status",    risk: 6, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Chase Bank",            legalEntity:"Ripple Treasury US LLC", approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_CHASE_USD1",      offsetNumber:"1234567890", attachment:{ name:"Contract-Scan.pdf",         type:"pdf", url:"https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" } },
  { id:"2334725",    payee:"German Traders",         type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_PROCESS",  amount:  18560.00, cur:"EUR", trnDate:"22/03/2025", valDate:"22/03/2025", status:"Extracted",        nextStatus:"Confirmed",        processStage:"Status",    risk: 4, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Deutsche Bank",         legalEntity:"Ripple Treasury EU GmbH",approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_DEUTSCHE_EUR",    offsetNumber:"5678901234" },
  { id:"2334726",    payee:"Atlantic Freight Co",    type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_PROCESS",  amount:  67450.00, cur:"USD", trnDate:"22/03/2025", valDate:"22/03/2025", status:"Extracted",        nextStatus:"Confirmed",        processStage:"Status",    risk: 5, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Wells Fargo",           legalEntity:"Ripple Treasury US LLC", approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_WELLS_USD",       offsetNumber:"1234567891" },
  { id:"2334730",    payee:"Nordic Shipping AS",     type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_CONFIRM",  amount:  45200.00, cur:"EUR", trnDate:"21/03/2025", valDate:"21/03/2025", status:"Confirmed",        nextStatus:"Approved",         processStage:"Status",    risk: 3, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"DNB ASA",               legalEntity:"Ripple Treasury EU GmbH",approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_DNB_EUR",         offsetNumber:"6012345001" },
  { id:"2334731",    payee:"Midwest Distribution",   type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_CONFIRM",  amount:  28750.50, cur:"USD", trnDate:"21/03/2025", valDate:"21/03/2025", status:"Confirmed",        nextStatus:"Approved",         processStage:"Status",    risk: 4, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Chase Bank",            legalEntity:"Ripple Treasury US LLC", approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_CHASE_USD1",      offsetNumber:"6012345002" },
  { id:"2334732",    payee:"Thames Valley Ltd",      type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_CONFIRM",  amount:  19800.00, cur:"GBP", trnDate:"21/03/2025", valDate:"21/03/2025", status:"Confirmed",        nextStatus:"Approved",         processStage:"Status",    risk: 5, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Barclays",              legalEntity:"Ripple Treasury UK Ltd", approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_BARCLAYS_GBP",    offsetNumber:"6012345003", attachment:{ name:"Bank-Confirmation.pdf",     type:"pdf", url:"https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" } },
  { id:"2334733",    payee:"Berlin Automotive GmbH", type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_CONFIRM",  amount:  82600.00, cur:"EUR", trnDate:"21/03/2025", valDate:"21/03/2025", status:"Confirmed",        nextStatus:"Approved",         processStage:"Status",    risk: 2, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Deutsche Bank",         legalEntity:"Ripple Treasury EU GmbH",approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_DEUTSCHE_EUR",    offsetNumber:"6012345004" },
  { id:"2334528",    payee:"Retail Stores",          type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_FAILED",   amount:   7800.00, cur:"USD", trnDate:"21/03/2025", valDate:"21/03/2025", status:"Failed",           nextStatus:"—",                processStage:"Status",    risk:20, riskReason:"Beneficiary account closed",  riskFlag:null,       verified:true,  overdue:false, bank:"Chase Bank",            legalEntity:"Ripple Treasury US LLC", approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_CHASE_USD1",      offsetNumber:"8901234567" },
  { id:"2334529",    payee:"French Imports",          type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_FAILED",   amount:  12400.00, cur:"EUR", trnDate:"21/03/2025", valDate:"21/03/2025", status:"Failed",           nextStatus:"—",                processStage:"Status",    risk:18, riskReason:"Routing number invalid",      riskFlag:null,       verified:true,  overdue:false, bank:"BNP Paribas",           legalEntity:"Ripple Treasury EU GmbH",approver:"L. Kim",     approvalLevel:0, operativeAcct:"0A_BNP_EUR",         offsetNumber:"2345678901" },
  { id:"2334626",    payee:"Construction Corp",      type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_COMPLETE",  amount:  95000.00, cur:"USD", trnDate:"20/03/2025", valDate:"20/03/2025", status:"Approved",         nextStatus:"Complete",         processStage:"History",   risk: 5, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Bank of America",       legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:0, operativeAcct:"0A_BOA_USD",         offsetNumber:"3456789012", attachment:{ name:"Final-Invoice.pdf",         type:"pdf", url:"https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" } },
  { id:"2334627",    payee:"Consulting Group",        type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_COMPLETE",  amount:  42300.50, cur:"GBP", trnDate:"19/03/2025", valDate:"19/03/2025", status:"Approved",         nextStatus:"Complete",         processStage:"History",   risk: 3, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Lloyds Bank",           legalEntity:"Ripple Treasury UK Ltd", approver:"A. Pacheco", approvalLevel:0, operativeAcct:"0A_LLOYDS_GBP",      offsetNumber:"6789012345" },
  { id:"2334430",    payee:"Canceled Order",          type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_VOID",      amount:   5600.00, cur:"USD", trnDate:"18/03/2025", valDate:"18/03/2025", status:"Void",             nextStatus:"—",                processStage:"History",   risk: 2, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"Citibank",              legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:0, operativeAcct:"0A_CITI_USD",        offsetNumber:"4567890123" },
  { id:"2334431",    payee:"Withdrawn Service",       type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_VOID",      amount:   9200.00, cur:"GBP", trnDate:"17/03/2025", valDate:"17/03/2025", status:"Void",             nextStatus:"—",                processStage:"History",   risk: 3, riskReason:null,                          riskFlag:null,       verified:true,  overdue:false, bank:"NatWest",               legalEntity:"Ripple Treasury UK Ltd", approver:"A. Pacheco", approvalLevel:0, operativeAcct:"0A_NATWEST_GBP",     offsetNumber:"7890123456" },
  { id:"2334901",    payee:"Apex Engineering",        type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_CREATE",    amount:  14500.00, cur:"USD", trnDate:"26/02/2026", valDate:"26/02/2026", status:"Draft",            nextStatus:"Submit for Review", processStage:"Create",    risk: 5, riskReason:null,                          riskFlag:null,       verified:false, overdue:false, bank:"Chase Bank",     legalEntity:"Ripple Treasury LLC",    approver:"A. Pacheco", approvalLevel:0, operativeAcct:"0A_CHASE_USD1",      offsetNumber:"3012345678" },
  { id:"2334902",    payee:"Nordic Imports",          type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_CREATE",    amount:   8250.00, cur:"EUR", trnDate:"26/02/2026", valDate:"26/02/2026", status:"Draft",            nextStatus:"Submit for Review", processStage:"Create",    risk: 3, riskReason:null,                          riskFlag:null,       verified:false, overdue:false, bank:"HSBC Europe",    legalEntity:"Ripple Treasury EU GmbH",approver:"A. Pacheco", approvalLevel:0, operativeAcct:"0A_HSBC_EUR",        offsetNumber:"3012345679" },
  { id:"2334903",    payee:"Pacific Logistics",       type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_CREATE",    amount:  22800.00, cur:"USD", trnDate:"25/02/2026", valDate:"25/02/2026", status:"Draft",            nextStatus:"Submit for Review", processStage:"Create",    risk: 8, riskReason:null,                          riskFlag:null,       verified:false, overdue:false, bank:"Wells Fargo",    legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:0, operativeAcct:"0A_WELLS_USD",       offsetNumber:"3012345680" },
  { id:"2334904",    payee:"Meridian Capital",        type:"Wire", instType:"WIRE",     modelId:"WIRE_CREATE",        amount: 135000.00, cur:"USD", trnDate:"25/02/2026", valDate:"25/02/2026", status:"Draft",            nextStatus:"Submit for Review", processStage:"Create",    risk:12, riskReason:null,                          riskFlag:null,       verified:false, overdue:false, bank:"JPMorgan Chase", legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:0, operativeAcct:"Master (****1234)",  offsetNumber:"3012345681" },
  { id:"2334905",    payee:"Brisbane Partners",       type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_CREATE",    amount:  31200.00, cur:"GBP", trnDate:"24/02/2026", valDate:"24/02/2026", status:"Draft",            nextStatus:"Submit for Review", processStage:"Create",    risk: 6, riskReason:null,                          riskFlag:null,       verified:false, overdue:false, bank:"Barclays",       legalEntity:"Ripple Treasury UK Ltd", approver:"A. Pacheco", approvalLevel:0, operativeAcct:"0A_BARCLAYS_GBP",    offsetNumber:"3012345682" },
  { id:"AF-100101",  payee:"Horizon Trading Co",      type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_FRAUD",     amount:  48200.00, cur:"USD", trnDate:"26/02/2026", valDate:"26/02/2026", status:"Under Review",     nextStatus:"Approve / Reject",  processStage:"Anti Fraud",risk:78, riskReason:"Unusual destination country",    riskFlag:"HIGH",     verified:false, overdue:true, bank:"Chase Bank",     legalEntity:"Ripple Treasury LLC",    approver:"A. Pacheco", approvalLevel:1, operativeAcct:"0A_CHASE_USD1",      offsetNumber:"4012345601" },
  { id:"AF-100102",  payee:"Meridian Exports Ltd",    type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_FRAUD",     amount:  92400.00, cur:"EUR", trnDate:"26/02/2026", valDate:"26/02/2026", status:"Under Review",     nextStatus:"Approve / Reject",  processStage:"Anti Fraud",risk:85, riskReason:"Velocity alert: 3rd wire today", riskFlag:"HIGH",     verified:false, overdue:true, bank:"HSBC Europe",    legalEntity:"Ripple Treasury EU GmbH",approver:"A. Pacheco", approvalLevel:1, operativeAcct:"0A_HSBC_EUR",        offsetNumber:"4012345602" },
  { id:"AF-100103",  payee:"Eastern Capital Group",   type:"Wire", instType:"WIRE",     modelId:"WIRE_FRAUD",         amount: 250000.00, cur:"USD", trnDate:"25/02/2026", valDate:"25/02/2026", status:"Under Review",     nextStatus:"Approve / Reject",  processStage:"Anti Fraud",risk:92, riskReason:"Sanctioned entity match",        riskFlag:"CRIT",     verified:false, overdue:true, bank:"JPMorgan Chase", legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:2, operativeAcct:"Master (****1234)",  offsetNumber:"4012345603" },
  { id:"AF-100104",  payee:"Silvergate Consulting",   type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_FRAUD",     amount:  18750.00, cur:"GBP", trnDate:"26/02/2026", valDate:"26/02/2026", status:"Under Review",     nextStatus:"Approve / Reject",  processStage:"Anti Fraud",risk:65, riskReason:"New beneficiary — first payment", riskFlag:"MED",      verified:false, overdue:true, bank:"Barclays",       legalEntity:"Ripple Treasury UK Ltd", approver:"A. Pacheco", approvalLevel:1, operativeAcct:"0A_BARCLAYS_GBP",    offsetNumber:"4012345604" },
  { id:"AF-100105",  payee:"Orion Global Corp",       type:"Wire", instType:"WIRE",     modelId:"WIRE_FRAUD",         amount: 175000.00, cur:"USD", trnDate:"25/02/2026", valDate:"25/02/2026", status:"Under Review",     nextStatus:"Approve / Reject",  processStage:"Anti Fraud",risk:88, riskReason:"Amount 3× account average",      riskFlag:"HIGH",     verified:false, overdue:true, bank:"Wells Fargo",    legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:2, operativeAcct:"0A_WELLS_USD",       offsetNumber:"4012345605" },
  { id:"AF-100106",  payee:"Navarro Supply Co",       type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_FRAUD",     amount:   9300.00, cur:"EUR", trnDate:"26/02/2026", valDate:"26/02/2026", status:"Under Review",     nextStatus:"Approve / Reject",  processStage:"Anti Fraud",risk:55, riskReason:"AML screening — pending review", riskFlag:"MED",      verified:false, overdue:true, bank:"BNP Paribas",    legalEntity:"Ripple Treasury EU GmbH",approver:"A. Pacheco", approvalLevel:1, operativeAcct:"0A_BNP_EUR",         offsetNumber:"4012345606" },
  { id:"AF-100107",  payee:"Vantage Freight Ltd",     type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_FRAUD",     amount:  62500.00, cur:"USD", trnDate:"25/02/2026", valDate:"25/02/2026", status:"Under Review",     nextStatus:"Approve / Reject",  processStage:"Anti Fraud",risk:72, riskReason:"Duplicate payment reference",    riskFlag:"HIGH",     verified:false, overdue:true, bank:"Chase Bank",     legalEntity:"Ripple Treasury LLC",    approver:"A. Pacheco", approvalLevel:1, operativeAcct:"0A_CHASE_USD1",      offsetNumber:"4012345607" },
  { id:"AF-100108",  payee:"Cascade Renewables",      type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_FRAUD",     amount:  34800.00, cur:"GBP", trnDate:"26/02/2026", valDate:"26/02/2026", status:"Under Review",     nextStatus:"Approve / Reject",  processStage:"Anti Fraud",risk:60, riskReason:"Counterparty jurisdiction risk", riskFlag:"MED",      verified:false, overdue:true, bank:"NatWest",        legalEntity:"Ripple Treasury UK Ltd", approver:"A. Pacheco", approvalLevel:1, operativeAcct:"0A_NATWEST_GBP",     offsetNumber:"4012345608" },
  { id:"AF-100109",  payee:"Summit Asset Partners",   type:"Wire", instType:"WIRE",     modelId:"WIRE_FRAUD",         amount: 480000.00, cur:"USD", trnDate:"24/02/2026", valDate:"24/02/2026", status:"Under Review",     nextStatus:"Approve / Reject",  processStage:"Anti Fraud",risk:95, riskReason:"High-risk beneficiary profile",  riskFlag:"CRIT",     verified:false, overdue:true, bank:"JPMorgan Chase", legalEntity:"Ripple Treasury US LLC", approver:"A. Pacheco", approvalLevel:2, operativeAcct:"Master (****1234)",  offsetNumber:"4012345609" },
  { id:"AF-100110",  payee:"Titan Procurement SA",    type:"Wire", instType:"PL_E_PAY", modelId:"PL_E_PAY_FRAUD",     amount:  27600.00, cur:"EUR", trnDate:"26/02/2026", valDate:"26/02/2026", status:"Under Review",     nextStatus:"Approve / Reject",  processStage:"Anti Fraud",risk:68, riskReason:"Structuring pattern detected",   riskFlag:"HIGH",     verified:false, overdue:true, bank:"Deutsche Bank",  legalEntity:"Ripple Treasury EU GmbH",approver:"A. Pacheco", approvalLevel:1, operativeAcct:"0A_DEUTSCHE_EUR",    offsetNumber:"4012345610" },
];

export const fmtAmt = (n: number, c: string) =>
  `${c==="EUR"?"€":c==="GBP"?"£":"$"}${n.toLocaleString("en-US",{minimumFractionDigits:2})}`;

export const FRAUD_DATA: FlaggedTxn[] = [
  { id:"1",  paymentNumber:"2766", vendor:"Trusted Partner Ltd",        corridor:"N/A",   currency:"GBP", amount:32000,    riskScore:81, riskLevel:"high",
    riskFactors:["First-Time Payee: No prior transaction history with this recipient","High-Risk Countries: Beneficiary bank located in sanctioned jurisdiction","Amount Outlier: Payment 4.2x above historical average for this corridor"],
    recommendation:"HIGH RISK — Multiple risk factors identified. Manual review and authorization required." },
  { id:"2",  paymentNumber:"2785", vendor:"Regular Supplier",           corridor:"N/A",   currency:"EUR", amount:200000,   riskScore:46, riskLevel:"medium",
    riskFactors:["Amount Outlier: Payment exceeds 2x typical range for this beneficiary","Off-Hours Check: Submitted at 23:47 outside business hours (09:00–17:00)"],
    recommendation:"MEDIUM RISK — Amount exceeds typical range and submitted after hours. Recommend additional verification before proceeding." },
  { id:"3",  paymentNumber:"2763", vendor:"Widget Manufacturing Co",    corridor:"N/A",   currency:"CAD", amount:45750,    riskScore:85, riskLevel:"high",
    riskFactors:["First-Time Payee: New unverified beneficiary with no transaction history","High-Risk Countries: Routing through elevated-risk jurisdiction (Cayman Islands)","Amount Outlier: First payment to this vendor exceeds $40,000 threshold"],
    recommendation:"HIGH RISK — Multiple risk factors identified. Manual review and authorization required." },
  { id:"4",  paymentNumber:"2767", vendor:"Suspicious Entity Inc",      corridor:"N/A",   currency:"USD", amount:500000,   riskScore:92, riskLevel:"critical",
    riskFactors:["High-Risk Countries: Beneficiary in FATF-listed jurisdiction with sanctions exposure","Velocity Check: 5 payments to same beneficiary in 24 hours (threshold: 3)","Amount Outlier: Payment 8x above historical average","First-Time Payee: No prior relationship — shell company indicators detected"],
    recommendation:"CRITICAL RISK — Immediate review required. Transaction blocked pending manual authorization." },
  { id:"5",  paymentNumber:"2790", vendor:"Global Logistics Corp",      corridor:"US → US", currency:"USD", amount:125000, riskScore:78, riskLevel:"high",
    riskFactors:["Velocity Check: Duplicate payment detected — same amount and beneficiary within 2 hours","Amount Outlier: Payment 3x above 90-day average for this vendor","Off-Hours Check: Submitted at 02:15 outside business hours (09:00–17:00)"],
    recommendation:"HIGH RISK — Duplicate payment pattern with off-hours submission. Manual review required before release." },
  { id:"6",  paymentNumber:"2791", vendor:"Offshore Trading Group",     corridor:"US → KY", currency:"USD", amount:750000, riskScore:95, riskLevel:"critical",
    riskFactors:["High-Risk Countries: FATF high-risk jurisdiction (Cayman Islands) with sanctions list match (91%)","First-Time Payee: Nominee structure detected — no prior transaction history","Velocity Check: 7 payments across 3 related entities in 48 hours","Amount Outlier: Single payment exceeds $500,000 threshold","Off-Hours Check: Submitted at 01:30 outside business hours (09:00–17:00)"],
    recommendation:"CRITICAL RISK — Immediate void required. Nominee structure with sanctions match. File SAR." },
  { id:"7",  paymentNumber:"2792", vendor:"MedTech Solutions",          corridor:"US → IN", currency:"INR", amount:8500000, riskScore:52, riskLevel:"medium",
    riskFactors:["First-Time Payee: New beneficiary with no prior transaction history","High-Risk Countries: Cross-border payment to emerging market jurisdiction"],
    recommendation:"MEDIUM RISK — First-time beneficiary in emerging market. Recommend EDD before approval." },
  { id:"8",  paymentNumber:"2793", vendor:"Nordic Energy AS",           corridor:"US → NO", currency:"NOK", amount:1200000, riskScore:88, riskLevel:"critical",
    riskFactors:["Amount Outlier: Invoice amount 3x historical average for this vendor","High-Risk Countries: Beneficiary bank changed to high-risk jurisdiction","Velocity Check: Approval chain bypassed — 4 payments submitted in rapid succession","Off-Hours Check: Submitted at 04:22 outside business hours (09:00–17:00)"],
    recommendation:"CRITICAL RISK — BEC attack indicators present. Transaction blocked pending security review and out-of-band confirmation with vendor." },
  { id:"9",  paymentNumber:"2794", vendor:"Pacific Rim Holdings",       corridor:"US → HK", currency:"HKD", amount:2400000, riskScore:72, riskLevel:"high",
    riskFactors:["First-Time Payee: New beneficiary with no prior transaction history","Amount Outlier: Payment 2.5x above historical average for this corridor"],
    recommendation:"HIGH RISK — First-time payee with elevated amount. Manual review recommended." },
  { id:"10", paymentNumber:"2795", vendor:"Quantum Financial Services", corridor:"US → SG", currency:"SGD", amount:680000, riskScore:58, riskLevel:"medium",
    riskFactors:["Velocity Check: 3 payments to same beneficiary within 6 hours","Off-Hours Check: Submitted at 22:10 outside business hours (09:00–17:00)"],
    recommendation:"MEDIUM RISK — Velocity pattern with off-hours submission. Additional verification recommended." },
  { id:"11", paymentNumber:"2796", vendor:"Atlas Infrastructure Corp",  corridor:"US → AE", currency:"AED", amount:3200000, riskScore:83, riskLevel:"high",
    riskFactors:["High-Risk Countries: Beneficiary in UAE free trade zone with limited transparency","Amount Outlier: Single payment exceeds $800,000 threshold","First-Time Payee: No prior relationship — complex ownership structure detected"],
    recommendation:"HIGH RISK — Complex ownership with high-risk jurisdiction. Enhanced due diligence required before approval." },
];

export const VERIF_DATA: Record<string, { av?: VerifAV; kyb?: VerifKYB }> = {
  "2766": {
    av:  { status:"pass",    confidence:94, recommendation:"Safe to proceed with transaction", checks:[{label:"Account active and operational",passed:true},{label:"No fraud alerts on file",passed:true},{label:"Not on sanctions / PEP lists",passed:true},{label:"Name match: 94% confidence",passed:true}] },
    kyb: { risk:"low",    status:"COMPLIANT",                     assessment:"Legitimate, well-established entity with clean regulatory record. All checks passed.", actions:[] } },
  "2785": {
    av:  { status:"warning", confidence:67, recommendation:"Request documentation to confirm legal business name", checks:[{label:"Account active and operational",passed:true},{label:"Name match: 67% (S.A. suffix mismatch)",passed:false},{label:"Account type: Savings (unusual for B2B)",passed:false},{label:"Account opened < 3 years ago",passed:false}] },
    kyb: { risk:"medium", status:"REQUIRES ADDITIONAL DILIGENCE", assessment:"UBO data unavailable. Potential OFAC sanctions match at 85% confidence. Company registration unverified.", actions:["Obtain UBO Declaration Form","Confirm sanctions list false positive","Request Certificate of Incorporation"] } },
  "2763": {
    av:  { status:"warning", confidence:58, recommendation:"Clarify name discrepancy before proceeding", checks:[{label:"Account active and operational",passed:true},{label:"Name match: 58% (Co vs Company Inc)",passed:false},{label:"Account type: Savings (unusual for B2B)",passed:false}] },
    kyb: { risk:"medium", status:"REQUIRES ADDITIONAL DILIGENCE", assessment:"Relatively new business. Name discrepancy warrants clarification. Minor adverse media found but resolved.", actions:["Clarify name discrepancy","Request updated business registration"] } },
  "2767": {
    av:  { status:"fail",    confidence:31, recommendation:"DO NOT PROCEED — escalate immediately", checks:[{label:"Account status: FROZEN",passed:false},{label:"Fraud alert flagged by bank (Dec 2025)",passed:false},{label:"Found on internal watchlist (Jan 2026)",passed:false},{label:"Name match: 31% confidence",passed:false}] },
    kyb: { risk:"high",   status:"NON-COMPLIANT",                 assessment:"OFAC SDN match at 98%. Active money laundering investigation. Entity presents unacceptable compliance risk.", actions:["Freeze transaction immediately","File SAR","Notify OFAC within 10 days","Escalate to Chief Compliance Officer"] } },
  "2790": {
    av:  { status:"warning", confidence:62, recommendation:"Confirm account change with vendor via verified contact before releasing", checks:[{label:"Account active and operational",passed:true},{label:"Duplicate payment detected",passed:false},{label:"Beneficiary account changed within 72 hours",passed:false},{label:"Payment velocity: 3 payments in 24 hours",passed:false}] },
    kyb: { risk:"medium", status:"REQUIRES ADDITIONAL DILIGENCE", assessment:"Established company but duplicate payment pattern and recent customs investigation warrant additional review.", actions:["Verify no duplicate payment","Confirm account change with vendor","Review customs investigation status"] } },
  "2791": {
    av:  { status:"fail",    confidence:22, recommendation:"DO NOT PROCEED — void transaction immediately", checks:[{label:"Account status: FROZEN",passed:false},{label:"Multiple SAR filings associated",passed:false},{label:"Name match: 22% — nominee structure detected",passed:false}] },
    kyb: { risk:"high",   status:"NON-COMPLIANT",                 assessment:"Extremely high risk. Nominee structure with OFAC SDN match (91%) and active money laundering investigation. Void immediately.", actions:["Void transaction","File SAR","Escalate to CCO","Freeze related accounts"] } },
  "2792": {
    av:  { status:"warning", confidence:71, recommendation:"Verify beneficiary details with sender before proceeding", checks:[{label:"Account active and operational",passed:true},{label:"Name match: 71% (Pvt Ltd suffix added)",passed:true},{label:"First-time payment to this beneficiary",passed:false}] },
    kyb: { risk:"medium", status:"REQUIRES ADDITIONAL DILIGENCE", assessment:"Legitimate but new company. First-time beneficiary warrants standard enhanced due diligence for initial transaction.", actions:["Verify beneficiary details with originator","Request proforma invoice or contract"] } },
  "2793": {
    av:  { status:"fail",    confidence:28, recommendation:"DO NOT PROCEED — Strong BEC indicators. Contact vendor via known phone number immediately.", checks:[{label:"Account NOT at expected bank (DNB ASA)",passed:false},{label:"Account opened 47 days ago — newly created",passed:false},{label:"Name match: 28% — different entity name",passed:false},{label:"CEO email domain mismatch detected",passed:false}] },
    kyb: { risk:"high",   status:"NON-COMPLIANT",                 assessment:"CRITICAL — Strong BEC attack indicators. Bank changed Norway → Cyprus. Name mismatch with shell entity. DO NOT release funds.", actions:["Block payment immediately","Contact Nordic Energy AS via verified phone","Report BEC attempt to FBI IC3","Review all recent payment instructions from this vendor"] } },
};

export const ANOMALY_PFXS = ["Amount Outlier"];
export const isAnomaly = (f: string) => ANOMALY_PFXS.some(p => f.startsWith(p));
export const displayScore = (t: FlaggedTxn) => t.riskFactors.some(f => !isAnomaly(f)) ? t.riskScore : Math.min(t.riskScore, 70);
export const primaryTrigger = (factors: string[]) => {
  const f = factors.find(x => !isAnomaly(x)) ?? factors[0] ?? "";
  if (f.startsWith("First-Time Payee"))    return "New Beneficiary";
  if (f.startsWith("High-Risk Countries")) return "High-Risk Jurisdiction";
  if (f.startsWith("Velocity Check"))      return "Velocity Flag";
  if (f.startsWith("Off-Hours"))           return "Off-Hours";
  if (f.startsWith("Amount Outlier"))      return "Unusual Amount";
  return "Flagged";
};
export const scoreColors = (score: number, anomalyOnly: boolean) =>
  anomalyOnly                  ? { dot:"bg-amber-400",   text:"text-amber-400",   label:"Anomaly Detected" }
  : score >= 90                ? { dot:"bg-red-500",     text:"text-red-400",     label:"Critical Risk"    }
  : score >= 75                ? { dot:"bg-orange-500",  text:"text-orange-400",  label:"High Risk"        }
  : score >= 50                ? { dot:"bg-amber-500",   text:"text-amber-400",   label:"Medium Risk"      }
  :                              { dot:"bg-emerald-500", text:"text-emerald-400", label:"Low Risk"         };
export const fmtFlagAmt = (amt: number, cur: string) => {
  const sym: Record<string,string> = {USD:"$",EUR:"€",GBP:"£",CAD:"C$",HKD:"HK$",SGD:"S$",NOK:"kr ",INR:"₹",AED:"AED "};
  return `${sym[cur]??cur+" "}${amt.toLocaleString("en-US")}`;
};

export const DEFERRED_SUMMARY_ROWS: SummaryRow[] = [
  { id:"pending-fraud-review", label:"Pending fraud review", statusFilter:"Under Review",     Icon:ShieldAlert, iconColor:"text-rose-400",    iconBg:"bg-rose-500/15",    debits:1298550.00,     credits:0,            amount:1298550.00,     count:10  },
];

export const SUMMARY_ROWS: SummaryRow[] = [
  { id:"approval-needed",      label:"Approval needed",      statusFilter:"Needs Approval",   Icon:Clock,       iconColor:"text-amber-400",   iconBg:"bg-amber-500/15",   debits:14350.75,       credits:0,            amount:14350.75,       count:11  },
  { id:"ready-to-extract",     label:"Ready to extract",     statusFilter:"Ready to Extract", Icon:ArrowUpRight,iconColor:"text-teal-400",    iconBg:"bg-teal-500/15",    debits:5234182.50,     credits:1128640.00,   amount:6362822.50,     count:47  },
  { id:"extracted",            label:"Extracted",            statusFilter:"Extracted",        Icon:CheckCircle2,iconColor:"text-blue-400",    iconBg:"bg-blue-500/15",    debits:37807355.65,    credits:22170426.91,  amount:59977782.56,    count:275 },
  { id:"confirmed",            label:"Confirmed",            statusFilter:"Confirmed",        Icon:CheckCircle2,iconColor:"text-indigo-400",  iconBg:"bg-indigo-500/15",  debits:28450120.33,    credits:15280445.12,  amount:43730565.45,    count:189 },
  { id:"completed",            label:"Completed",            statusFilter:"Approved",         Icon:CheckCircle2,iconColor:"text-emerald-400", iconBg:"bg-emerald-500/15", debits:81838589.67,    credits:18933320.49,  amount:100771910.16,   count:238 },
  { id:"failed",               label:"Failed",               statusFilter:"Failed",           Icon:X,           iconColor:"text-red-400",     iconBg:"bg-red-500/15",     debits:2882646.73,     credits:1630339.30,   amount:4512986.03,     count:172 },
  { id:"void",                 label:"Void",                 statusFilter:"Void",             Icon:Ban,         iconColor:"text-slate-400",   iconBg:"bg-slate-700/50",   debits:44058587.78,    credits:4067933.40,   amount:48126521.18,    count:96  },
];

export const ALL_COLS = {
  risk:"Risk", trnNum:"Trn. Number", trnDate:"Trn. Date", amount:"Amount",
  payee:"Beneficiary", operativeAcct:"Operative Account", instType:"Type",
  valDate:"Value Date", offsetNum:"Account No.",
};

export const DEFAULT_COLS = { risk:true, trnNum:true, trnDate:true, amount:true, payee:true, operativeAcct:true, instType:true, valDate:false, offsetNum:false };
